export const theme = {
  colors: {
    surface: '#fdf8f5',
    surfaceDim: '#ddd9d6',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f7f3ef',
    surfaceContainer: '#f1ede9',
    surfaceContainerHigh: '#ece7e4',
    onSurface: '#1c1b1a',
    onSurfaceVariant: '#4d4637',
    primary: '#775a01',
    onPrimary: '#ffffff',
    primaryContainer: '#c9a44c',
    onPrimaryContainer: '#4f3b00',
    secondary: '#795912',
    secondaryContainer: '#fdd17f',
    onSecondaryContainer: '#785811',
    tertiary: '#3c6847',
    tertiaryContainer: '#85b48e',
    tertiaryFixed: '#bdeec5',
    onTertiaryFixedVariant: '#244f31',
    error: '#ba1a1a',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    outline: '#7f7665',
    outlineVariant: '#d1c5b2',
    primaryFixed: '#ffdf9a',
    secondaryFixed: '#ffdea6',
    onSecondaryFixed: '#271900'
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 14,
    lg: 20,
    xl: 28,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    full: 9999,
  }
};
